config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{PluginRoutes.all_locales}/, :defaults => {} do
    # frontend
    namespace :plugins do
      namespace 'ecommerce' do
        controller :front do
          get 'login'
          post 'login' => :do_login
          get 'register'
          post 'register' => :do_register
        end

        scope :checkout, as: :checkout do
          controller 'front/checkout' do
            get 'success_paypal'
            get 'cancel_paypal'
            post 'pay_by_bank_transfer'
            post 'pay_by_credit_card'
            post 'pay_by_authorize_net'
            post 'pay_by_stripe'
            post 'pay_by_paypal'
            post 'pay_by_on_delivery'
          end
        end

        get 'checkout' => 'front/checkout#index'
        post 'checkout/step_address' => 'front/checkout#step_address'
        post 'checkout/step_shipping' => 'front/checkout#step_shipping'
        get 'checkout/cart' => 'front/checkout#cart_index'
        get 'checkout/complete_free_order' => 'front/checkout#complete_free_order'
        post 'checkout/cart/add' => 'front/checkout#cart_add'
        post 'checkout/cart/update' => 'front/checkout#cart_update'
        get 'checkout/cart/remove' => 'front/checkout#cart_remove'
        post 'res_coupon' => 'front/checkout#res_coupon'
        get 'orders' => 'front/orders#index'
        get 'orders/:order/show' => 'front/orders#show', as: :order_show
      end
    end
  end

  #Admin Panel
  scope 'admin', as: 'admin' do
    namespace 'plugins' do
      namespace 'ecommerce' do
        get 'index' => 'admin#index'
        get 'product_attributes' => 'admin#product_attributes'
        post 'product_attributes' => 'admin#save_product_attributes'
        resources :orders, controller: 'admin/orders' do
          get 'mark_accepted'
          get 'resend_email'
          get 'mark_bank_confirmed'
          post 'mark_shipped'
          post 'mark_canceled'
        end
        resources :payment_methods, controller: 'admin/payment_methods'
        resources :shipping_methods, controller: 'admin/shipping_methods' do
          resources :prices, controller: 'admin/prices'
        end
        resources :coupons, controller: 'admin/coupons'
        resources :tax_rates, controller: 'admin/tax_rates'
        get 'settings' => 'admin/settings#index'
        post 'settings/saved' => 'admin/settings#saved'
      end
    end
  end

  # main routes
  #scope 'ecommerce', module: 'plugins/ecommerce/', as: 'ecommerce' do
  #  Here my routes for main routes
  #end
end

app/controllers/plugins/ecommerce/front/checkout_controller.rb
class Plugins::Ecommerce::Front::CheckoutController < Plugins::Ecommerce::FrontController
  before_action :commerce_authenticate, except: [:cart_add, :cart_update, :cart_remove, :cart_index]
  before_action :set_cart
  before_action :set_payment, only: [:pay_by_stripe, :pay_by_bank_transfer, :pay_by_credit_card, :pay_by_authorize_net, :pay_by_paypal, :pay_by_on_delivery]

  def index
    unless @cart.product_items.count > 0
      flash[:cama_ecommerce][:notice] = t('plugins.ecommerce.messages.cart_no_products', default: 'Not exist products in your cart')
      return redirect_to action: :cart_index
    end
    @ecommerce_breadcrumb << [t('plugins.ecommerce.messages.checkout', default: 'Checkout')]
  end

  def step_address
    @cart.set_meta("billing_address", params[:order][:billing_address])
    @cart.set_meta("shipping_address", params[:order][:shipping_address])
    render nothing: true
  end

  def step_shipping
    @cart.update_column(:shipping_method_id, params[:shipping_method])
    if params[:next_step].present?
      render partial: plugin_view('partials/checkout/payments'), layout: false
    else
      render partial: plugin_view('partials/checkout/products_detail'), layout: false
    end
  end

  # free carts
  def complete_free_order
    if @cart.free_cart?
      errors = ecommerce_verify_cart_errors(@cart)
      if errors.present?
        flash[:cama_ecommerce][:error] = errors.join('<br>')
        redirect_to :back
      else
        hooks_run('plugin_ecommerce_before_complete_free_order', @cart)
        @cart.set_meta('free_order', true)
        commerce_mark_cart_received(@cart)
        hooks_run('plugin_ecommerce_after_complete_free_order', @cart)
        redirect_to plugins_ecommerce_orders_path
      end
    else
      flash[:cama_ecommerce][:error] = "Invalid complete payment"
      redirect_to :back
    end
  end

  def cart_index
    @products = @cart.product_items.decorate
    @ecommerce_breadcrumb << [t('plugins.ecommerce.messages.shopping_cart', default: 'Shopping cart')]
  end

  def res_coupon
    code = params[:code].to_s.downcase
    res = @cart.discount_for(code)
    if res[:error].present?
      render inline: commerce_coupon_error_message(res[:error], res[:coupon]), status: 500
    else
      @cart.update_column(:coupon, code)
      render partial: plugin_view('partials/checkout/products_detail'), layout: false
    end
  end

  # params[cart]: product_id,  qty
  def cart_add
    data = params[:cart]
    qty = data[:qty].to_f rescue 0
    product = current_site.products.find(data[:product_id]).decorate
    unless product.valid_variation?(params[:variation_id])
      flash[:cama_ecommerce][:error] = t('plugins.ecommerce.messages.missing_variation', default: 'Invalid Product Variation')
      return params[:format] == 'json' ? render(json: flash.discard(:cama_ecommerce).to_hash) : (redirect_to action: :cart_index)
    end

    unless product.can_added?(qty, params[:variation_id])
      flash[:cama_ecommerce][:error] =  t('plugins.ecommerce.messages.not_enough_product_qty', product: product.the_variation_title(params[:variation_id]), qty: product.the_qty(params[:variation_id]), default: 'There is not enough products "%{product}" (Available %{qty})')
      return params[:format] == 'json' ? render(json: flash.discard(:cama_ecommerce).to_hash) : (redirect_to :back)
    end
    @cart.add_product(product, qty, params[:variation_id])
    flash[:cama_ecommerce][:notice] = t('plugins.ecommerce.messages.added_product_in_cart', default: 'Product added into cart')
    params[:format] == 'json' ? render(json: flash.discard(:cama_ecommerce).to_hash) : (redirect_to action: :cart_index)
  end

  def cart_update
    errors = []
    params[:product_items].each do |data|
      item =  @cart.product_items.find(data[:item_id])
      product = item.product.decorate
      qty = data[:qty].to_f
      if product.can_added?(qty, item.variation_id)
        @cart.add_product(product, qty, item.variation_id)
      else
        errors << t('plugins.ecommerce.messages.not_enough_product_qty', product: product.the_variation_title(item.variation_id), qty: product.the_qty(item.variation_id), default: 'There is not enough products "%{product}" (Available %{qty})')
      end
    end
    flash[:cama_ecommerce][:error] = errors.join('<br>') if errors.present?
    flash[:cama_ecommerce][:notice] = t('plugins.ecommerce.messages.cart_updated', default: 'Shopping cart updated') unless errors.present?
    params[:format] == 'json' ? render(json: flash.discard(:cama_ecommerce).to_hash) : (redirect_to action: :cart_index)
  end

  def cart_remove
    @cart.product_items.find(params[:product_item_id]).destroy
    flash[:cama_ecommerce][:notice] = t('plugins.ecommerce.messages.cart_deleted', default: 'Product removed from your shopping cart')
    params[:format] == 'json' ? render(json: flash.discard(:cama_ecommerce).to_hash) : (redirect_to action: :cart_index)
  end

  def cancel_order
    @cart.update({status: 'canceled', kind: 'order', closed_at: Time.now})
    flash[:cama_ecommerce][:notice] = t('plugins.ecommerce.messages.canceled_order', default: "Canceled Order")
    params[:format] == 'json' ? render(json: flash.discard(:cama_ecommerce).to_hash) : (redirect_to plugins_ecommerce_orders_url)
  end

  def pay_by_stripe
    result = Plugins::Ecommerce::CartService.new(current_site, @cart).
      pay_with_stripe(payment_method: @payment,
        email: params[:stripeEmail],
        stripe_token: params[:stripeToken],
      )
    if result[:error].present?
      flash[:cama_ecommerce][:error] = result[:error]
      if result[:payment_error]
        flash[:payment_error] = true
      end
      redirect_to :back
    else
      commerce_mark_cart_received(@cart)
      redirect_to plugins_ecommerce_orders_url
    end
  end

  def pay_by_bank_transfer
    @cart.set_meta("payment_data", params[:details])
    commerce_mark_cart_received(@cart, 'bank_pending')
    redirect_to plugins_ecommerce_orders_url
  end

  def pay_by_on_delivery
    @cart.set_meta("payment_data", params[:details])
    commerce_mark_cart_received(@cart, 'on_delivery')
    redirect_to plugins_ecommerce_orders_url
  end

  def pay_by_authorize_net
    res = Plugins::Ecommerce::CartService.new(current_site, @cart).
      pay_with_authorize_net(payment_method: @payment, ip: request.remote_ip,
        first_name: params[:firstName],
        last_name: params[:lastName],
        number: params[:cardNumber],
        exp_month: params[:expMonth],
        exp_year: params[:expYear],
        cvc: params[:cvCode],
      )
    if res[:error].present?
      flash[:cama_ecommerce][:error] = res[:error]
      flash[:payment_error] = true
      redirect_to :back
    else
      commerce_mark_cart_received(@cart)
      redirect_to plugins_ecommerce_orders_url
    end
  end

  def success_paypal
    response = @cart.paypal_gateway.purchase(Plugins::Ecommerce::UtilService.ecommerce_money_to_cents(@cart.total_amount), {
      :ip => request.remote_ip,
      :token => params[:token],
      :payer_id => params[:PayerID]
    })

    if response.success?
      @cart.set_meta('payment_data', {token: params[:token], PayerID: params[:PayerID], ip: request.remote_ip})
      commerce_mark_cart_received(@cart)
    else
      flash[:cama_ecommerce][:error] = response.message
    end
    redirect_to plugins_ecommerce_orders_url
  end

  def cancel_paypal
    redirect_to plugins_ecommerce_orders_url
  end

  def pay_by_paypal
    result = Plugins::Ecommerce::CartService.new(current_site, @cart).
      pay_with_paypal(ip: request.remote_ip, return_url: plugins_ecommerce_checkout_success_paypal_url(order: @cart.slug), cancel_return_url: plugins_ecommerce_checkout_cancel_paypal_url(order: @cart.slug))
    redirect_to result[:redirect_url]
  end

  private
  def set_cart
    @cart = e_current_cart
  end

  def set_bread
    @ecommerce_breadcrumb << [t('plugins.ecommerce.messages.checkout', default: 'Checkout'), url_for(action: :cart_index)]
  end

  def set_payment
    @payment = current_site.payment_methods.actives.where(id: params[:payment][:payment_id]).first
    @cart.update_column(:payment_method_id, @payment.id)
  end
end

app/controllers/plugins/ecommerce/front/orders_controller.rb
class Plugins::Ecommerce::Front::OrdersController < Plugins::Ecommerce::FrontController
  before_action :commerce_authenticate
  before_action :set_bread
  def index
    @orders = current_site.orders.set_user(cama_current_user).decorate
    render "index"
  end

  def show
    @order = current_site.orders.set_user(cama_current_user).find_by_slug(params[:order]).try(:decorate)
    return redirect_to(url_for(action: :index), error: t('plugins.ecommerce.messages.order_not_found', default: "Order not found", order: params[:order])) unless @order.present?
    @ecommerce_breadcrumb << [t('plugins.ecommerce.messages.detail_order', default: "Detail order: #%{order}", order: params[:order])]
  end

  private
  def set_bread
    @ecommerce_breadcrumb << [t('plugins.ecommerce.messages.my_orders', default: 'My Orders'), url_for(action: :index)]
  end
end

app/controllers/plugins/ecommerce/front_controller.rb
class Plugins::Ecommerce::FrontController < CamaleonCms::Apps::PluginsFrontController
  prepend_before_action :init_flash
  before_action :ecommerce_add_assets_in_front
  before_action :save_cache_redirect, only: [:login, :register]
  def login
    @user ||= current_site.users.new
    render 'login'
  end

  def do_login
    if login_user_with_password(params[:email], params[:password])
      callback_login(@user)
      login_user(@user, false, (cookies[:e_return_to] || plugins_ecommerce_orders_path))
      return cookies.delete(:e_return_to)
    else
      flash[:cama_ecommerce][:error] = t('plugins.ecommerce.messages.invalid_access', default: 'Invalid access')
      return login
    end
  end

  def register
    params[:kind_form] = 'register-form'
    @user ||= current_site.users.new
    render 'login'
  end

  def do_register
    params[:camaleon_cms_user][:username] = params[:camaleon_cms_user][:email] if params[:camaleon_cms_user].present?
    @user = current_site.users.new(params.require(:camaleon_cms_user).permit(:first_name, :last_name, :username, :email, :password, :password_confirmation))
    if @user.save
      flash[:cama_ecommerce][:notice] = t('plugins.ecommerce.messages.created_account', default: "Account created successfully")
      callback_login(@user)
      login_user(@user, false, (cookies[:e_return_to] || plugins_ecommerce_orders_path))
      return cookies.delete(:e_return_to)
    else
      return register
    end
  end

  private
  def save_cache_redirect
    cookies[:e_return_to] = params[:return_to] if params[:return_to].present?
  end

  def commerce_authenticate
    unless cama_sign_in?
      flash[:cama_ecommerce][:error] = t('camaleon_cms.admin.login.please_login')
      cookies[:e_return_to] = request.referer
      redirect_to plugins_ecommerce_login_path
    end
  end

  def init_flash
    flash[:cama_ecommerce] = {} unless flash[:cama_ecommerce].present?
  end

  # callback after log in
  def callback_login(user)
    if cookies[:e_cart_id].present?
      e_current_cart(ecommerce_get_visitor_key).change_user(user)
      cookies.delete(:e_cart_id)
    end
  end
end

app/views/plugins/ecommerce/front/checkout/cart_index.html.erb
<div class="cart_view">
    <%= render 'post_types/commerce/cart_widget' %>
  <h1><%= t('.title', default: 'Shopping Cart') %></h1>
  <%= form_tag(plugins_ecommerce_checkout_cart_update_path, :method => "post", :class => "form") do %>
      <table id="table-shopping-cart" class="table table-bordered">
          <thead>
          <tr>
              <th id="item_col"><%= t('.item', default: 'Item') %></th>
              <th id="price_col"><%= t('.price', default: 'Price') %></th>
              <th id="price_col"><%= t('.tax', default: 'Tax') %></th>
              <th id="quantity_col"><%= t('.quantity', default: 'Quantity') %></th>
              <th id="subtotal_col"><%= t('.subtotal', default: 'Subtotal') %></th>
              <th></th>
          </tr>
          </thead>
          <tbody>
          <% @products.each do |item| product = item.product.decorate %>
              <tr>
                  <td><a href="<%= item.the_url %>"><%= item.the_title %></a></td>
                  <td><%= item.the_price %></td>
                  <td><%= item.the_tax %></td>
                  <td>
                      <input name="product_items[][item_id]" type="hidden" value="<%= item.id %>"/>
                      <input class="text-qty" type="number" name="product_items[][qty]" value="<%= item.qty %>">
                  </td>
                  <td><%= item.the_sub_total %></td>
                  <td>
                      <a rel="nofollow" data-method="delete" href="<%= plugins_ecommerce_checkout_cart_remove_path(product_item_id: item.id) %>"><%= t('.delete', default: 'Remove') %></a>
                  </td>
              </tr>
          <% end %>
          </tbody>
          <tfoot>
          <tr>
              <td colspan="4"></td>
              <td><%= t('.subtotal', default: 'Subtotal') %></td>
              <td><%= @cart.the_total_amount %></td>
          </tr>
          </tfoot>
      </table>
      <% if @products.size > 0 %>
          <div class="text-right">
              <button type="submit" class="btn btn-default"> <%= t('.update', default: 'Update') %> </button>
              <a class="btn btn-info" href="<%= plugins_ecommerce_checkout_path %>"><i class="fa fa-shopping-cart"></i> <%= t('.proceed', default: 'Proceed to Checkout') %></a>
          </div>
      <% end %>
  <% end %>
</div>

app/views/plugins/ecommerce/front/checkout/index.html.erb
<% cama_load_custom_assets({"plugin_ecommerce"=>{css: [plugin_asset("checkout")] } }) %>
<% if warning.present? %>
    <div class="alert alert-danger"><%= raw warning.join("<br>") %></div>
<% end %>
<div id="cama_checkout_view" class="row checkout_view">
    <%= render 'post_types/commerce/cart_widget' %>
    <h1><%= t('.check_out_process', default: 'Checkout Process') %></h1>
    <div class="stepwizard col-md-offset-3 col-sm-offset-3">
        <div class="stepwizard-row setup-panel">
            <div class="stepwizard-step">
                <a href="#step-1" type="button" class="btn btn-default btn-circle" disabled="disabled">1</a>
                <p><%= t('.step', default: 'Step') %> 1</p>
            </div>
            <div class="stepwizard-step">
                <a href="#step-2" type="button" class="btn btn-default btn-circle" disabled="disabled">2</a>
                <p><%= t('.step', default: 'Step') %> 2</p>
            </div>
            <div class="stepwizard-step">
                <a href="#step-3" type="button" class="btn btn-default btn-circle" disabled="disabled">3</a>
                <p><%= t('.step', default: 'Step') %> 3</p>
            </div>
        </div>
    </div>

    <div class="steps_content">
        <div class="row setup-content" id="step-1">
            <%= form_tag(plugins_ecommerce_checkout_step_address_path, :method => "post", :class => "col-md-12", id: 'checkout_address_form') do %>
                <%= render plugin_view('partials/checkout/user_info') %>
                <div class="clearfix"></div>
            <% end %>
        </div>
        <div class="row setup-content" id="step-2">
            <%= form_tag(plugins_ecommerce_checkout_step_shipping_path, :method => "post", :class => "col-md-12", id: 'checkout_shipping_form') do %>
                <%= render plugin_view('partials/checkout/details') %>
            <% end %>
        </div>
        <div class="row setup-content" id="step-3">

        </div>
    </div>
</div>
<script>jQuery(function(){ cama_checkout_actions(); <% if flash[:payment_error].present? %> setTimeout(function(){ $('#cama_checkout_view #checkout_shipping_form').submit(); }, 200); <% end %> })</script>