config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{PluginRoutes.all_locales}/, :defaults => {} do
    # frontend
    namespace :plugins do
      namespace 'ecommerce' do
        controller :front do
          get 'login'
          post 'login' => :do_login
          get 'register'
          post 'register' => :do_register
        end

        scope :checkout, as: :checkout do
          controller 'front/checkout' do
            get 'success_paypal'
            get 'cancel_paypal'
            post 'pay_by_bank_transfer'
            post 'pay_by_credit_card'
            post 'pay_by_authorize_net'
            post 'pay_by_stripe'
            post 'pay_by_paypal'
            post 'pay_by_on_delivery'
          end
        end

        get 'checkout' => 'front/checkout#index'
        post 'checkout/step_address' => 'front/checkout#step_address'
        post 'checkout/step_shipping' => 'front/checkout#step_shipping'
        get 'checkout/cart' => 'front/checkout#cart_index'
        get 'checkout/complete_free_order' => 'front/checkout#complete_free_order'
        post 'checkout/cart/add' => 'front/checkout#cart_add'
        post 'checkout/cart/update' => 'front/checkout#cart_update'
        get 'checkout/cart/remove' => 'front/checkout#cart_remove'
        post 'res_coupon' => 'front/checkout#res_coupon'
        get 'orders' => 'front/orders#index'
        get 'orders/:order/show' => 'front/orders#show', as: :order_show
      end
    end
  end

  #Admin Panel
  scope 'admin', as: 'admin' do
    namespace 'plugins' do
      namespace 'ecommerce' do
        get 'index' => 'admin#index'
        get 'product_attributes' => 'admin#product_attributes'
        post 'product_attributes' => 'admin#save_product_attributes'
        resources :orders, controller: 'admin/orders' do
          get 'mark_accepted'
          get 'resend_email'
          get 'mark_bank_confirmed'
          post 'mark_shipped'
          post 'mark_canceled'
        end
        resources :payment_methods, controller: 'admin/payment_methods'
        resources :shipping_methods, controller: 'admin/shipping_methods' do
          resources :prices, controller: 'admin/prices'
        end
        resources :coupons, controller: 'admin/coupons'
        resources :tax_rates, controller: 'admin/tax_rates'
        get 'settings' => 'admin/settings#index'
        post 'settings/saved' => 'admin/settings#saved'
      end
    end
  end

  # main routes
  #scope 'ecommerce', module: 'plugins/ecommerce/', as: 'ecommerce' do
  #  Here my routes for main routes
  #end
end

app/models/plugins/ecommerce/order.rb
class Plugins::Ecommerce::Order < Plugins::Ecommerce::Cart
  self.table_name = 'plugins_ecommerce_orders'
  has_many :metas, ->{ where(object_class: 'Plugins::Ecommerce::Cart')}, :class_name => "CamaleonCms::Meta", foreign_key: :objectid, dependent: :delete_all
  default_scope { where(kind: 'order') }
  # status:
  #         bank_pending => pending of verification for bank transfer orders
  #         on_delivery => pending to mark as paid after after delivery
  #         paid => paid by some method
  #         canceled => canceled order
  #         shipped => shipped status
  #         accepted => received status

  def paid?
    status == 'paid'
  end

  def accepted?
    status == 'accepted'
  end

  def shipped?
    status == 'shipped'
  end

  def canceled?
    status == 'canceled'
  end

  def received?
    status == 'received'
  end

  def bank_pending?
    status == 'bank_pending'
  end

  def on_delivery_pending?
    status == 'on_delivery'
  end

  def payment_data
    get_meta('payment_data', {})
  end

  # return the date of the current status
  def action_date
    case object.status
      when 'paid'
        object.created_at
      when 'canceled'
        object.closed_at
      when 'shipped'
        object.shipped_at
      when 'accepted'
        object.accepted_at
    end
  end
end

app/controllers/plugins/ecommerce/admin/orders_controller.rb
class Plugins::Ecommerce::Admin::OrdersController < Plugins::Ecommerce::AdminController
  before_action :set_order, except: [:index, :new] #, only: ['show', 'edit', 'update', 'destroy']
  before_action :set_order_bread

  def index
    @q = current_site.orders.order('received_at desc').ransack(params[:q])
    @orders = @q.result.paginate(:page => params[:page], :per_page => current_site.admin_per_page)
  end

  def show
    @order = @order.decorate
    add_breadcrumb("#{t('plugins.ecommerce.details_order', default: 'Order details')} - #{@order.slug}")
  end

  def new
    @order = current_site.orders.new
    render 'form'
  end

  def edit
    add_breadcrumb("#{t('camaleon_cms.admin.button.edit', default: 'Edit')}")
    render 'form'
  end

  def update
    hooks_run('plugin_ecommerce_before_update_order', @order)
    @order.set_meta("billing_address", params[:order][:billing_address])
    @order.set_meta("shipping_address", params[:order][:shipping_address])
    @order.set_metas(params[:metas])
    @order.update(params.require(:plugins_ecommerce_order).permit(:shipped_at))
    hooks_run('plugin_ecommerce_after_destroy_order', @order)
    flash[:notice] = "#{t('plugins.ecommerce.message.order_updated', default: 'Order Updated')}"
    redirect_to action: :show, id: params[:id]
  end

  def destroy
    hooks_run('plugin_ecommerce_before_destroy_order', @order)
    if @order.destroy
      flash[:notice] = "#{t('plugins.ecommerce.message.order_destroyed', default: 'Order Destroyed')}"
    else
      flash[:error] = "#{t('plugins.ecommerce.message.order_no_destroyed', default: 'Occurred some problems destroying the order')}"
    end
    hooks_run('plugin_ecommerce_after_destroy_order', @order)
    redirect_to action: :index
  end

  # accepted order
  def mark_accepted
    r = {order: @order}; hooks_run('plugin_ecommerce_before_accepted_order', r)
    @order.accepted!
    commerce_order_send_mail(@order, 'email_order_accepted')
    message = "#{t('plugins.ecommerce.message.order_accepted', default: 'Order Accepted')}"
    r = {order: @order, message: message}; hooks_run('plugin_ecommerce_after_accepted_order', r)
    flash[:notice] = r[:message]
    redirect_to action: :index
  end

  def mark_bank_confirmed
    if @order.on_delivery_pending?
      hooks_run('plugin_ecommerce_before_on_delivery_order', @order)
      @order.on_delivery_confirmed!
      commerce_order_send_mail(@order, 'email_order_confirmed_on_delivery')
      flash[:notice] = "#{t('plugins.ecommerce.message.order_on_delivery_confirmed', default: 'Payment on Delivery Confirmed')}"
      hooks_run('plugin_ecommerce_after_on_delivery_order', @order)
    else
      hooks_run('plugin_ecommerce_before_bank_confirm_order', @order)
      @order.bank_confirmed!
      commerce_order_send_mail(@order, 'email_order_confirmed_bank')
      flash[:notice] = "#{t('plugins.ecommerce.message.order_bank_confirmed', default: 'Pay Bank Confirmed')}"
      hooks_run('plugin_ecommerce_after_bank_confirm_order', @order)
    end
    redirect_to action: :index
  end

  # shipped order
  def mark_shipped
    hooks_run('plugin_ecommerce_before_shipped_order', @order)
    @order.shipped!(params[:consignment_number])
    commerce_order_send_mail(@order, 'email_order_shipped')
    flash[:notice] = "#{t('plugins.ecommerce.message.order_shipped', default: 'Order Shipped')}"
    hooks_run('plugin_ecommerce_after_shipped_order', @order)
    redirect_to action: :index
  end

  def mark_canceled
    hooks_run('plugin_ecommerce_before_canceled_order', @order)
    @order.canceled!
    @order.set_meta('description', params[:description])
    commerce_order_send_mail(@order, 'email_order_cancelled')
    flash[:notice] = "#{t('plugins.ecommerce.message.order_canceled', default: 'Order canceled')}"
    hooks_run('plugin_ecommerce_after_canceled_order', @order)
    redirect_to action: :index
  end

  def resend_email
    case @order.status
      when 'paid', 'bank_pending', 'on_delivery'
        commerce_order_send_mail(@order)
      when 'shipped'
        commerce_order_send_mail(@order, 'email_order_shipped')
      when 'canceled'
        commerce_order_send_mail(@order, 'email_order_cancelled')
      else
        flash[:error] = "#{t('plugins.ecommerce.message.unknown_status', default: 'Unknown Status')}"
        redirect_to action: :index
        return
    end
    flash[:notice] = "#{t('plugins.ecommerce.message.order_email_resent', default: 'Order Email Resent')}"
    redirect_to action: :index
  end

  private
  def set_order
    @order = current_site.orders.find_by_slug(params[:id] || params[:order_id]).decorate
  end

  def set_order_bread
    add_breadcrumb I18n.t("plugins.ecommerce.orders", default: 'Orders'), admin_plugins_ecommerce_orders_path
  end

end

app/controllers/plugins/ecommerce/front/checkout_controller.rb
class Plugins::Ecommerce::Front::CheckoutController < Plugins::Ecommerce::FrontController
  before_action :commerce_authenticate, except: [:cart_add, :cart_update, :cart_remove, :cart_index]
  before_action :set_cart
  before_action :set_payment, only: [:pay_by_stripe, :pay_by_bank_transfer, :pay_by_credit_card, :pay_by_authorize_net, :pay_by_paypal, :pay_by_on_delivery]

  def index
    unless @cart.product_items.count > 0
      flash[:cama_ecommerce][:notice] = t('plugins.ecommerce.messages.cart_no_products', default: 'Not exist products in your cart')
      return redirect_to action: :cart_index
    end
    @ecommerce_breadcrumb << [t('plugins.ecommerce.messages.checkout', default: 'Checkout')]
  end

  def step_address
    @cart.set_meta("billing_address", params[:order][:billing_address])
    @cart.set_meta("shipping_address", params[:order][:shipping_address])
    render nothing: true
  end

  def step_shipping
    @cart.update_column(:shipping_method_id, params[:shipping_method])
    if params[:next_step].present?
      render partial: plugin_view('partials/checkout/payments'), layout: false
    else
      render partial: plugin_view('partials/checkout/products_detail'), layout: false
    end
  end

  # free carts
  def complete_free_order
    if @cart.free_cart?
      errors = ecommerce_verify_cart_errors(@cart)
      if errors.present?
        flash[:cama_ecommerce][:error] = errors.join('<br>')
        redirect_to :back
      else
        hooks_run('plugin_ecommerce_before_complete_free_order', @cart)
        @cart.set_meta('free_order', true)
        commerce_mark_cart_received(@cart)
        hooks_run('plugin_ecommerce_after_complete_free_order', @cart)
        redirect_to plugins_ecommerce_orders_path
      end
    else
      flash[:cama_ecommerce][:error] = "Invalid complete payment"
      redirect_to :back
    end
  end

  def cart_index
    @products = @cart.product_items.decorate
    @ecommerce_breadcrumb << [t('plugins.ecommerce.messages.shopping_cart', default: 'Shopping cart')]
  end

  def res_coupon
    code = params[:code].to_s.downcase
    res = @cart.discount_for(code)
    if res[:error].present?
      render inline: commerce_coupon_error_message(res[:error], res[:coupon]), status: 500
    else
      @cart.update_column(:coupon, code)
      render partial: plugin_view('partials/checkout/products_detail'), layout: false
    end
  end

  # params[cart]: product_id,  qty
  def cart_add
    data = params[:cart]
    qty = data[:qty].to_f rescue 0
    product = current_site.products.find(data[:product_id]).decorate
    unless product.valid_variation?(params[:variation_id])
      flash[:cama_ecommerce][:error] = t('plugins.ecommerce.messages.missing_variation', default: 'Invalid Product Variation')
      return params[:format] == 'json' ? render(json: flash.discard(:cama_ecommerce).to_hash) : (redirect_to action: :cart_index)
    end

    unless product.can_added?(qty, params[:variation_id])
      flash[:cama_ecommerce][:error] =  t('plugins.ecommerce.messages.not_enough_product_qty', product: product.the_variation_title(params[:variation_id]), qty: product.the_qty(params[:variation_id]), default: 'There is not enough products "%{product}" (Available %{qty})')
      return params[:format] == 'json' ? render(json: flash.discard(:cama_ecommerce).to_hash) : (redirect_to :back)
    end
    @cart.add_product(product, qty, params[:variation_id])
    flash[:cama_ecommerce][:notice] = t('plugins.ecommerce.messages.added_product_in_cart', default: 'Product added into cart')
    params[:format] == 'json' ? render(json: flash.discard(:cama_ecommerce).to_hash) : (redirect_to action: :cart_index)
  end

  def cart_update
    errors = []
    params[:product_items].each do |data|
      item =  @cart.product_items.find(data[:item_id])
      product = item.product.decorate
      qty = data[:qty].to_f
      if product.can_added?(qty, item.variation_id)
        @cart.add_product(product, qty, item.variation_id)
      else
        errors << t('plugins.ecommerce.messages.not_enough_product_qty', product: product.the_variation_title(item.variation_id), qty: product.the_qty(item.variation_id), default: 'There is not enough products "%{product}" (Available %{qty})')
      end
    end
    flash[:cama_ecommerce][:error] = errors.join('<br>') if errors.present?
    flash[:cama_ecommerce][:notice] = t('plugins.ecommerce.messages.cart_updated', default: 'Shopping cart updated') unless errors.present?
    params[:format] == 'json' ? render(json: flash.discard(:cama_ecommerce).to_hash) : (redirect_to action: :cart_index)
  end

  def cart_remove
    @cart.product_items.find(params[:product_item_id]).destroy
    flash[:cama_ecommerce][:notice] = t('plugins.ecommerce.messages.cart_deleted', default: 'Product removed from your shopping cart')
    params[:format] == 'json' ? render(json: flash.discard(:cama_ecommerce).to_hash) : (redirect_to action: :cart_index)
  end

  def cancel_order
    @cart.update({status: 'canceled', kind: 'order', closed_at: Time.now})
    flash[:cama_ecommerce][:notice] = t('plugins.ecommerce.messages.canceled_order', default: "Canceled Order")
    params[:format] == 'json' ? render(json: flash.discard(:cama_ecommerce).to_hash) : (redirect_to plugins_ecommerce_orders_url)
  end

  def pay_by_stripe
    result = Plugins::Ecommerce::CartService.new(current_site, @cart).
      pay_with_stripe(payment_method: @payment,
        email: params[:stripeEmail],
        stripe_token: params[:stripeToken],
      )
    if result[:error].present?
      flash[:cama_ecommerce][:error] = result[:error]
      if result[:payment_error]
        flash[:payment_error] = true
      end
      redirect_to :back
    else
      commerce_mark_cart_received(@cart)
      redirect_to plugins_ecommerce_orders_url
    end
  end

  def pay_by_bank_transfer
    @cart.set_meta("payment_data", params[:details])
    commerce_mark_cart_received(@cart, 'bank_pending')
    redirect_to plugins_ecommerce_orders_url
  end

  def pay_by_on_delivery
    @cart.set_meta("payment_data", params[:details])
    commerce_mark_cart_received(@cart, 'on_delivery')
    redirect_to plugins_ecommerce_orders_url
  end

  def pay_by_authorize_net
    res = Plugins::Ecommerce::CartService.new(current_site, @cart).
      pay_with_authorize_net(payment_method: @payment, ip: request.remote_ip,
        first_name: params[:firstName],
        last_name: params[:lastName],
        number: params[:cardNumber],
        exp_month: params[:expMonth],
        exp_year: params[:expYear],
        cvc: params[:cvCode],
      )
    if res[:error].present?
      flash[:cama_ecommerce][:error] = res[:error]
      flash[:payment_error] = true
      redirect_to :back
    else
      commerce_mark_cart_received(@cart)
      redirect_to plugins_ecommerce_orders_url
    end
  end

  def success_paypal
    response = @cart.paypal_gateway.purchase(Plugins::Ecommerce::UtilService.ecommerce_money_to_cents(@cart.total_amount), {
      :ip => request.remote_ip,
      :token => params[:token],
      :payer_id => params[:PayerID]
    })

    if response.success?
      @cart.set_meta('payment_data', {token: params[:token], PayerID: params[:PayerID], ip: request.remote_ip})
      commerce_mark_cart_received(@cart)
    else
      flash[:cama_ecommerce][:error] = response.message
    end
    redirect_to plugins_ecommerce_orders_url
  end

  def cancel_paypal
    redirect_to plugins_ecommerce_orders_url
  end

  def pay_by_paypal
    result = Plugins::Ecommerce::CartService.new(current_site, @cart).
      pay_with_paypal(ip: request.remote_ip, return_url: plugins_ecommerce_checkout_success_paypal_url(order: @cart.slug), cancel_return_url: plugins_ecommerce_checkout_cancel_paypal_url(order: @cart.slug))
    redirect_to result[:redirect_url]
  end

  private
  def set_cart
    @cart = e_current_cart
  end

  def set_bread
    @ecommerce_breadcrumb << [t('plugins.ecommerce.messages.checkout', default: 'Checkout'), url_for(action: :cart_index)]
  end

  def set_payment
    @payment = current_site.payment_methods.actives.where(id: params[:payment][:payment_id]).first
    @cart.update_column(:payment_method_id, @payment.id)
  end
end

app/controllers/plugins/ecommerce/front/orders_controller.rb
class Plugins::Ecommerce::Front::OrdersController < Plugins::Ecommerce::FrontController
  before_action :commerce_authenticate
  before_action :set_bread
  def index
    @orders = current_site.orders.set_user(cama_current_user).decorate
    render "index"
  end

  def show
    @order = current_site.orders.set_user(cama_current_user).find_by_slug(params[:order]).try(:decorate)
    return redirect_to(url_for(action: :index), error: t('plugins.ecommerce.messages.order_not_found', default: "Order not found", order: params[:order])) unless @order.present?
    @ecommerce_breadcrumb << [t('plugins.ecommerce.messages.detail_order', default: "Detail order: #%{order}", order: params[:order])]
  end

  private
  def set_bread
    @ecommerce_breadcrumb << [t('plugins.ecommerce.messages.my_orders', default: 'My Orders'), url_for(action: :index)]
  end
end

app/views/plugins/ecommerce/front/orders/index.html.erb
<%= render 'post_types/commerce/cart_widget' %>
<h2><%= t('.title', default: 'My Orders') %></h2>
<table id="table-shopping-cart" class="table">
  <thead>
  <tr>
    <th><%= t('.id', default: 'ID') %></th>
    <th><%= t('.status', default: 'Status') %></th>
    <th><%= t('.products', default: 'Products') %></th>
    <th><%= t('.total_amount', default: 'Total Amount') %></th>
    <th><%= t('.coupon', default: 'Coupon') %></th>
    <th><%= t('.paid_amount', default: 'Paid Amount') %></th>
    <th><%= t('.order_date', default: 'Order Date') %></th>
    <th><%= t('.method', default: 'Payment Method') %></th>
    <th style="width: 90px"></th>
  </tr>
  </thead>
  <tbody>
  <% @orders.each do |order| %>
      <tr>
        <td><%= order.slug %></td>
        <td><%= raw order.the_status  %></td>
        <td>
          <% order.product_items.each do |item| %>
              <%= item.qty %> x <%= item.cache_the_title %> (<%= item.cache_the_price %>) <br>
          <% end %>
        </td>
        <td><%= order.cache_the_sub_total  %></td>
        <td><%= order.cache_the_discounts  %></td>
        <td><%= order.cache_the_total  %></td>
        <td><%= order.the_paid_at %></td>
        <td><%= order.payment_method.name rescue '' %></td>
        <td>
          <a href="<%= plugins_ecommerce_order_show_path(order: order.slug) %>" class="btn btn-default btn-xs"><%= t('.view', default: 'View') %></a>
        </td>
      </tr>
  <% end  %>
  </tbody>
</table>

app/views/plugins/ecommerce/front/orders/show.html.erb
<% order ||= @order %>
<div class="order_details">
    <% unless defined?(as_partial) %>
        <%= raw ecommerce_draw_breadcrumb %>
        <h1><%= t('.title', default: 'Order Details') %>: <%= order.slug %></h1>
    <% end %>
    <div class="basic_info">
        <% if order.invoice_number.present? %><b><%= t('.invoice_number', default: 'Invoice Number') %>: </b> <%= order.invoice_number %><br> <% end %>
        <% if order.received_at.present? %><b><%= t('.received_at', default: 'Received At') %>: </b> <%= order.the_received_at %><br> <% end %>
        <b><%= t('.created_at', default: 'Created At') %>: </b> <%= order.created_at %><br>
        <% if order.shipped_at.present? %><b><%= t('.shipped_at', default: 'Shipped At') %>: </b> <%= order.the_shipped_at %><br> <% end %>
    </div>
    <div>
        <h4><%= t('.customer_info', default: 'Customer Info') %></h4>
        <ul class="ec-list-orders-address">
            <li><strong><%= t('.name', default: 'Name') %>:</strong> <span> <%= order.user.fullname %></span></li>
            <li><strong><%= t('.email', default: 'Email') %>:</strong> <span> <%= order.user.email %></span></li>
            <li><strong><%= t('.phone', default: 'Phone') %>:</strong>
                <span> <%= order.user.get_option('phone') %></span></li>
        </ul>
    </div>

    <div class="row">
        <div class="col-md-6">
            <h4><%= t('.billing_address', default: 'Billing Address') %></h4>
            <% detail = order.get_meta("billing_address", {}) %>
            <ul class="ec-list-orders-address">
                <li><strong><%= t('.address', default: 'Address') %>1:</strong> <%= detail[:address1] %></li>
                <li><strong><%= t('.address', default: 'Address') %>2:</strong> <%= detail[:address2] %></li>
                <li><strong><%= t('.city', default: 'City') %>:</strong> <%= detail[:city] %></li>
                <li><strong><%= t('.state', default: 'State') %>:</strong> <%= detail[:state] %></li>
                <li><strong><%= t('.zip_code', default: 'Zip code') %>:</strong> <%= detail[:zip] %></li>
                <li><strong><%= t('.country', default: 'Country') %>:</strong> <%= detail[:country] %></li>
                <li><strong><%= t('.phone_number', default: 'Phone Number') %>:</strong> <%= detail[:phone_number] %>
                </li>
            </ul>
        </div>
        <div class="col-md-6">
            <h4><%= t('.shipping_address', default: 'Shipping Address') %></h4>
            <% detail = order.get_meta("shipping_address", {}) %>
            <ul class="ec-list-orders-address">
                <li><strong><%= t('.address', default: 'Address') %>1:</strong> <%= detail[:address1] %></li>
                <li><strong><%= t('.address', default: 'Address') %>2:</strong> <%= detail[:address2] %></li>
                <li><strong><%= t('.city', default: 'City') %>:</strong> <%= detail[:city] %></li>
                <li><strong><%= t('.state', default: 'State') %>:</strong> <%= detail[:state] %></li>
                <li><strong><%= t('.zip_code', default: 'Zip code') %>:</strong> <%= detail[:zip] %></li>
                <li><strong><%= t('.country', default: 'Country') %>:</strong> <%= detail[:country] %></li>
                <li><strong><%= t('.phone_number', default: 'Phone Number') %>:</strong> <%= detail[:phone_number] %>
                </li>
            </ul>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <h4><%= t('.title_products', default: 'Products and Payments') %></h4>
            <div id="totals_section">
                <table class="table table-bordered">
                    <tbody>
                    <tr>
                        <th><%= t('.qty', default: 'Quantity') %></th>
                        <th><%= t('.item', default: 'Item') %></th>
                        <th><%= t('.price', default: 'Price') %></th>

                        <th><%= t('.tax', default: 'Tax') %></th>
                        <th><%= t('.subtotal', default: 'Sub Total') %></th>
                    </tr>
                    <% order.product_items.decorate.each do |item| %>
                        <tr>
                            <td><%= item.qty %></td>
                            <td><%= link_to(item.cache_the_title, item.the_url) %></td>
                            <td><%= item.cache_the_price %></td>
                            <td><%= item.cache_the_tax %></td>
                            <td><%= item.cache_the_sub_total %></td>
                        </tr>
                    <% end %>
                    <tr>
                        <td colspan="2"></td>
                        <td colspan="2" class="text-right"><%= t('.total_excl', default: 'Total (excluding Tax)') %> </td>
                        <td><%= order.cache_the_sub_total %></td>
                    </tr>
                    <tr>
                        <td colspan="2"></td>
                        <td colspan="2" class="text-right"><%= t('.tax', default: 'Tax') %></td>
                        <td id="tax_total"><%= order.cache_the_tax %></td>
                    </tr>
                    <tr>
                        <td colspan="2"></td>
                        <td colspan="2" class="text-right"><%= t('.discount', default: 'Discount') %></td>
                        <td><%= order.cache_the_discounts %></td>
                    </tr>
                    <tr>
                        <td colspan="2"></td>
                        <td colspan="2" class="text-right"><%= t('.total_shipping', default: 'Total shipping') %></td>
                        <td><%= order.cache_the_shipping %></td>
                    </tr>
                    <tr>
                        <td colspan="2"></td>
                        <td colspan="2" class="text-right"><%= t('.total_price', default: 'Total Price') %></td>
                        <td><%= order.cache_the_total %></td>
                    </tr>
                    </tbody>
                </table>
            </div>

            <table class="table table-bordered">
                <tbody>
                <tr>
                    <th><%= t('.payment_type', default: 'Type Payment') %></th>
                    <th></th>
                </tr>
                <tr>
                    <td><%= order.payment_method.name rescue 'Not Payment' %></td>
                    <td><%= raw order.the_status %></td>
                </tr>
                <% if defined?(as_partial) %>
                    <tr>
                        <td>
                            <%= raw (order.get_meta('payment_data') || {}).map { |k, v| "<b>#{k.to_s.titleize}</b>: #{v}" }.join('<br>') %>
                        </td>
                    </tr>
                <% end %>
                </tbody>
            </table>

            <table class="table table-bordered">
                <tbody>
                <tr>
                    <th><%= t('.shipping_method', default: 'Shipping Method') %></th>
                    <th><%= t('.date_shipped', default: 'Shipped Date') %></th>
                    <th><%= t('.track_url', default: 'URL Tracking') %></th>
                </tr>
                <tr>
                    <td><%= order.the_shipping_method || t('.no_shipping', default: 'Not Shipped Assigned') %></td>
                    <td><%= order.shipped_at.presence || t('.no_shipped', default: 'Not Shipped') %></td>
                    <td><%= order.the_url_tracking %></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>