config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{PluginRoutes.all_locales}/, :defaults => {} do
    # frontend
    namespace :plugins do
      namespace 'ecommerce' do
        controller :front do
          get 'login'
          post 'login' => :do_login
          get 'register'
          post 'register' => :do_register
        end

        scope :checkout, as: :checkout do
          controller 'front/checkout' do
            get 'success_paypal'
            get 'cancel_paypal'
            post 'pay_by_bank_transfer'
            post 'pay_by_credit_card'
            post 'pay_by_authorize_net'
            post 'pay_by_stripe'
            post 'pay_by_paypal'
            post 'pay_by_on_delivery'
          end
        end

        get 'checkout' => 'front/checkout#index'
        post 'checkout/step_address' => 'front/checkout#step_address'
        post 'checkout/step_shipping' => 'front/checkout#step_shipping'
        get 'checkout/cart' => 'front/checkout#cart_index'
        get 'checkout/complete_free_order' => 'front/checkout#complete_free_order'
        post 'checkout/cart/add' => 'front/checkout#cart_add'
        post 'checkout/cart/update' => 'front/checkout#cart_update'
        get 'checkout/cart/remove' => 'front/checkout#cart_remove'
        post 'res_coupon' => 'front/checkout#res_coupon'
        get 'orders' => 'front/orders#index'
        get 'orders/:order/show' => 'front/orders#show', as: :order_show
      end
    end
  end

  #Admin Panel
  scope 'admin', as: 'admin' do
    namespace 'plugins' do
      namespace 'ecommerce' do
        get 'index' => 'admin#index'
        get 'product_attributes' => 'admin#product_attributes'
        post 'product_attributes' => 'admin#save_product_attributes'
        resources :orders, controller: 'admin/orders' do
          get 'mark_accepted'
          get 'resend_email'
          get 'mark_bank_confirmed'
          post 'mark_shipped'
          post 'mark_canceled'
        end
        resources :payment_methods, controller: 'admin/payment_methods'
        resources :shipping_methods, controller: 'admin/shipping_methods' do
          resources :prices, controller: 'admin/prices'
        end
        resources :coupons, controller: 'admin/coupons'
        resources :tax_rates, controller: 'admin/tax_rates'
        get 'settings' => 'admin/settings#index'
        post 'settings/saved' => 'admin/settings#saved'
      end
    end
  end

  # main routes
  #scope 'ecommerce', module: 'plugins/ecommerce/', as: 'ecommerce' do
  #  Here my routes for main routes
  #end
end

app/models/plugins/ecommerce/shipping_method.rb
class Plugins::Ecommerce::ShippingMethod < CamaleonCms::TermTaxonomy
  default_scope { where(taxonomy: :ecommerce_shipping_method) }
  belongs_to :site, :class_name => "CamaleonCms::Site", foreign_key: :parent_id
  scope :actives, -> {where(status: '1')}

  def skip_slug_validation?
    true
  end

  def get_price_from_weight(weight = 0)
    price_total = 0
    prices = get_meta("prices")
    if prices.present?
      prices.each do |key, value|
        price_total = value[:price] if value[:min_weight].to_f <= weight.to_f && value[:max_weight].to_f >= weight.to_f
      end
    end
    price_total.to_f
  end

end

app/controllers/plugins/ecommerce/admin/shipping_methods_controller.rb
class Plugins::Ecommerce::Admin::ShippingMethodsController < Plugins::Ecommerce::AdminController
  before_action :set_order, only: ['show','edit','update','destroy']

  def index
    @shipping_methods = current_site.shipping_methods.paginate(:page => params[:page], :per_page => current_site.admin_per_page)
  end

  def new
    @shipping_method = current_site.shipping_methods.new
    add_breadcrumb("#{t('plugins.ecommerce.new')}")
    render 'form'
  end

  def show
    add_breadcrumb("#{t('plugins.ecommerce.table.details')}")
  end

  def edit
    add_breadcrumb("#{t('camaleon_cms.admin.button.edit')}")
    render 'form'
  end

  def create
    @shipping_method = current_site.shipping_methods.new(shipping_permit_data)
    if @shipping_method.save
      @shipping_method.set_meta('_default',params[:options])
      flash[:notice] = t('camaleon_cms.admin.post_type.message.created')
      redirect_to action: :index
    else
      render 'form'
    end
  end

  def update
    if @shipping_method.update(shipping_permit_data)
      @shipping_method.set_meta('_default',params[:options])
      flash[:notice] = t('camaleon_cms.admin.post_type.message.updated')
      redirect_to action: :index
    else
      render 'form'
    end
  end


  private
  def set_order
    @shipping_method = current_site.shipping_methods.find(params[:id])
  end

  def shipping_permit_data
    params.require(:plugins_ecommerce_shipping_method).permit!
  end

end

app/views/plugins/ecommerce/admin/shipping_methods/form.html.erb
<div class="panel panel-default">
    <div class="panel-heading ui-draggable-handle">
        <h4><span class="fa fa-credit-card"></span> <%= @shipping_method.new_record? ? t('plugins.ecommerce.new_shipping_methods') : "#{t('plugins.ecommerce.edit_shipping_methods')}: #{@shipping_method.name}" %></h4>
    </div>
    <%= form_for @shipping_method, url:{action: @shipping_method.new_record? ? :create : :update},  html: {class: 'validate-shipping_method', id: 'form-shipping_method'}  do |f| %>
        <div class="panel-body">
            <%= render partial: 'layouts/camaleon_cms/admin/form_error', locals: {data: @shipping_method} %>
            <div class="form-group">
                <%= f.label t('plugins.ecommerce.table.name') %><br>
                <%= f.text_field :name, :class => "form-control required" %>
            </div>
            <div class="form-group">
                <%= f.label t('camaleon_cms.admin.table.description') %><br>
                <%= f.text_area :description, :class => "form-control translatable", :rows => 4 %>
            </div>

            <% options = @shipping_method.options rescue {url_tracking: 'http://trackingurl.com/track/{{consignment_number}}'}
               options = params[:options] if params[:options].present?
            %>
            <div class="form-group">
                <label><%= t('plugins.ecommerce.table.url_tracking') %></label><br>
                <%= text_field_tag( "options[url_tracking]", options[:url_tracking], class: "form-control required") %>
                <small><%= t('plugins.ecommerce.message.consignment_number') %></small>
            </div>

            <div class="form-group">
                <label><%= f.check_box :status %> &nbsp; <%= t('plugins.ecommerce.active') %></label>
            </div>
        </div>
        <div class="panel-footer">
            <a class="btn btn-default" href="<%= url_for action: :index %>" role="back"><%= t('camaleon_cms.admin.button.back')%></a>
            <button class="btn btn-primary pull-right" type="submit"><%= t('camaleon_cms.admin.button.submit')%></button>
        </div>
    <% end %>
</div>

app/views/plugins/ecommerce/admin/shipping_methods/index.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <h4><span class="fa fa-credit-card"></span> <%= t('plugins.ecommerce.shipping_methods') %> </h4>
        <%= link_to raw("<i class='fa fa-plus'></i> #{t('plugins.ecommerce.add_shipping_methods')}"), {action: :new}, class: "btn btn-primary pull-right" %>
    </div>
    <div class="panel-body">

        <table class="table">
            <thead>
            <tr>
                <th id=""><%= t('plugins.ecommerce.table.name') %></th>
                <th id=""><%= t('plugins.ecommerce.table.status') %></th>
                <th id=""><%= t('plugins.ecommerce.table.description') %></th>
                <th><%= t('plugins.ecommerce.table.actions') %></th>
            </tr>
            </thead>
            <tbody>
            <%
               @shipping_methods.each do |row|
            %>
                <tr>
                    <td><%= row.name.to_s.translate %></td>
                    <td><%= row.status %></td>
                    <td><%= row.description.to_s.translate  %></td>
                    <td>
                        <%= link_to raw('<i class="fa fa-usd"></i> ' + "#{t('plugins.ecommerce.shipping_prices', default: 'Prices')}"), admin_plugins_ecommerce_shipping_method_prices_path(row.id), class: "btn btn-primary btn-xs" %>
                        <%= link_to raw('<i class="fa fa-edit"></i>'), {action: :edit, id: row.id }, class: "btn btn-default btn-xs", title: "#{t('camaleon_cms.admin.button.edit')}" %>
                    </td>
                </tr>
            <% end  %>


            </tbody>
        </table>
        <%= content_tag("div", raw(t('camaleon_cms.admin.message.data_found_list')), class: "alert alert-warning") if @shipping_methods.empty? %>
        <%= will_paginate @shipping_methods, renderer: BootstrapPagination::Rails  %>
    </div>
</div>

app/views/plugins/ecommerce/admin/shipping_methods/show.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <h4><span class="fa fa-taxi"></span> <%= @shipping_method.name %></h4>
        <%= link_to raw("<i class='fa fa-edit'></i> #{t('plugins.ecommerce.edit_shipping_methods')}"), {action: :edit, id: @shipping_method.id}, class: "btn btn-primary pull-right" %>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-6">
                <h3><%= t('plugins.ecommerce.info') %></h3>
                <ul class="ec-list-orders-address">
                    <li><strong><%= t('plugins.ecommerce.table.name') %>:</strong> <span> <%= @shipping_method.name %></span></li>
                    <li><strong><%= t('plugins.ecommerce.table.description') %>:</strong> <span> <%= @shipping_method.description %></span></li>
                </ul>
            </div>

        </div>

    </div>
    <div class="panel-footer">
        <a class="btn btn-default" role="back" href="<%= url_for action: :index %>"><%= t('camaleon_cms.admin.button.back')%></a>
    </div>
</div>